sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345678
---
#redis
sky:
  redis:
    host: redis-17802.c44.us-east-1-2.ec2.redns.redis-cloud.com
    port: 17802
    password: df0nZvW6JXAHgcxkf9Vr3GDh8yvyQor8